# Scaffolding generated by Casein v5.1.1.5

module Casein
  class MixesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Mixes'
  		@mixes = Mix.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View mix'
      @mix = Mix.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new mix'
    	@mix = Mix.new
    end

    def create
      @mix = Mix.new mix_params
    
      if @mix.save
        flash[:notice] = 'Mix created'
        redirect_to casein_mixes_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new mix'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update mix'
      
      @mix = Mix.find params[:id]
    
      if @mix.update_attributes mix_params
        flash[:notice] = 'Mix has been updated'
        redirect_to casein_mixes_path
      else
        flash.now[:warning] = 'There were problems when trying to update this mix'
        render :action => :show
      end
    end
 
    def destroy
      @mix = Mix.find params[:id]

      @mix.destroy
      flash[:notice] = 'Mix has been deleted'
      redirect_to casein_mixes_path
    end
  
    private
      
      def mix_params
        params.require(:mix).permit(:name, :part)
      end

  end
end