development: &default
  adapter: postgresql
  database: MyApp_development
  username: vagrant
  password: vagrant
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: MyApp_test
